### ISSUE TITLE
Permissions with Forum 

### ISSUE THREAD

**Issue by linzster** [calliopeinitiative/marca#232]
permissions should be aligned with role in course instead of role in Emma.

ex. student/instructors can start discussions in the classes they are enrolled in.

**Comment by ssteger** [comment]
This is still an issue - instructors can start discussions no matter if they're a student in the course or an instructor in the course.  But I feel like it's such a one-off that we don't need to devote development time to the issue (it's only really classes like Deb's or Christy's that have TAs).
