### ISSUE TITLE
Arrangement of Markup Sets on Instructor Review

### ISSUE THREAD

**Issue by linzster** [calliopeinitiative/marca#251]
In the instructor review set-up, it seems like the default is to have the Presentation and Design markup tag set appear first and display, unlike the other rubric headers, which need to be clicked on to display the markup tags.  I wonder if this makes it too easy to mark grammar errors, and if the display may be nudging instructors to focus on grammar errors, which goes against best practice for feedback.  Thoughts?  This came up in our comp theory class, and I thought I would throw it out there.  An option would be to collapse the markup set behind a Presentation and Design button.

**Comment by ssteger** [comment]
Overhaul of markup in pipeline
