### ISSUE TITLE
Session disruption / ending notification

### ISSUE THREAD

**Issue by jweath** [calliopeinitiative/marca#255]
Based on conversation with students in class today, an enhancement to the connection interruption notifications we've implemented (which are great / appreciated):

Several students reported:
- Working on a doc in the docs editor
- Closing their laptops with the doc open
- Reopening their laptops and continuing work and clicking save
- Losing work done after reopening their laptops because their session had timed out

We could argue all day that students should know better (and perhaps they should), but would it be possible to check if the user's in an active session before clicking save, and if s/he isn't, popping up a login screen (maybe in a modal) and allowing them to save / not lose work?

**Comment by ssteger** [comment]
Fixed!
