### ISSUE TITLE
Possibility of a Praise Default Mark-up Set for Instructors

### ISSUE THREAD

**Issue by linzster** [calliopeinitiative/marca#260]
This issue also came up in composition theory with solid grounding in recent research on teacher feedback.  Praise has been found to be one of the most effective types of feedback for student writing, though not utilized a whole lot by instructors.  Maybe we could do a little nudging on this?  The availability of the markup might also encourage teachers to praise more in their comments.

**Comment by ssteger** [comment]
Overhaul of markup
