### ISSUE TITLE
Alphabetize "Presentation and Design" Markup set, both for UGA <emma> and in general

### ISSUE THREAD

**Issue by jweath** [calliopeinitiative/marca#268]
In the "Presentation and Design" Markup set in the UGA markup, the tag's aren't fully alphabetized. There are two alphabetized lists displayed sequentially. It'd be nice (especially on production <emma>, where I'm grading a good number of papers) to have a fully integrated list.

**Comment by ssteger** [comment]
Overhaul of markup in pipeline
