### ISSUE TITLE
Default view for Resources and Projects displays files from all units / projects

### ISSUE THREAD

**Issue by jweath** [calliopeinitiative/marca#301]
Multiple students have had a hard time finding resources not displayed under the first Resource unit.

Displaying Resources from all units (and docs/files/links from all projects) by default fits more closely with what seems to be our users' mental model: here are all of my things, and I can either just look through them all for the thing I want, or I can sort them with the menus on the left.

Anybody want to push back against me on this? I could be wrong, but I think this is the right direction to head.

**Comment by ssteger** [comment]
We no longer have defaults - change in UI
