### ISSUE TITLE
Project view / Project doc/file/upload create default project don't line up

### ISSUE THREAD

**Issue by jweath** [calliopeinitiative/marca#303]
The project you are viewing in right-hand project menu, and the project you upload to by default are NOT the same. If a user is in a "final project" project, but she doesn't select that radio button in the upload screen, her file is probably being sent to "paper 1" or whatever the first project is, and she's not seeing the upload show up. 

(via Andy)

**Comment by ssteger** [comment]
UI change - no more confusion
