### ISSUE TITLE
Add session check on Save and Close / Submit / etc.

### ISSUE THREAD

**Issue by jweath** [calliopeinitiative/marca#309]
If a user hasn't chosen "Remember Me," works on a document for a while, then steps away / stops work for long enough that the session closes, when s/he returns to work and clicks Save / Submit, s/he'll be taken to a login screen. Ideal behavior would be to have a session check built into Save / Submit so that if a session is current, everything goes as expected and if it's not, the user is prompted to log back in and his/her work is saved.

**Comment by ssteger** [comment]
Fixed with autosave and sessioning messaging
